//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsTable
    {
        public int Id { get; set; }
        public System.DateTime DateOfEvent { get; set; }
        public string NameOfEvent { get; set; }
        public int CoordinatesOfEvent { get; set; }
    }
}
