//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTable
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string EmailAdress { get; set; }
        public string EmailPassword { get; set; }
        public string Phone { get; set; }

        public UsersTable() { }

        public UsersTable(string login, string password, string role, string emailAdress, string emailPassword, string phone)
        {
            Login = login;
            Password = password;
            Role = role;
            EmailAdress = emailAdress;
            EmailPassword = emailPassword;
            Phone = phone;
        }
    }
}
